### ISSUE TITLE
Suffixes in Attacking SurrogateLLM Needed

### ISSUE THREAD

**Issue by Opdoop** [arobey1/smooth-llm#2]
Great work! 🎉
Could you kindly release the generated 50 attacked suffixes in Appendix C.3
This will help the community to quickly follow up and make the reproduction pain-free.
Thanks in advance.

**Comment by Opdoop** [comment]
I notice in https://github.com/arobey1/smooth-llm#experiments provides 10 suffixes. Its really helpful to release all 50 suffixes.

**Comment by arobey1** [comment]
Hello! We're glad that you enjoyed reading our work. 

It would be helpful if you could clarify which suffixes you're interested in.
* The suffixes described in Appendix C.3 are for the *adaptive attack* we derived, which we called SurrogateLLM
* The suffixes in https://github.com/arobey1/smooth-llm#experiments are for the *non-adaptive* GCG attack

**Comment by Opdoop** [comment]
@arobey1 Thanks for your quick response!!!
Sorry I confused these two data. I'm looking for the _adaptive attack_ suffixes.

**Comment by Opdoop** [comment]
Hello @arobey1. Is there any plan to release adaptive attack suffixes? If I understand correctly, publishing these suffixes is a piece of cake.

**Comment by Opdoop** [comment]
Hi @arobey1. Could you share more non-adaptive GCG attack suffixes instead? Ten seems a bit limited. Thanks for considering this request.

**Comment by zichuan-liu** [comment]
> Hi @arobey1. Could you share more non-adaptive GCG attack suffixes instead? Ten seems a bit limited. Thanks for considering this request.

Hi, did you solve it?, how can i  generate more attack data ny GCG attack

**Comment by Hephaestusxg** [comment]
> > Hi @arobey1. Could you share more non-adaptive GCG attack suffixes instead? Ten seems a bit limited. Thanks for considering this request.
> 
> Hi, did you solve it?, how can i generate more attack data ny GCG attack

so how to solve it？？
